// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMZYd6yj8Wpg-m43E71HhObEDPmWknysQ',
    appId: '1:223831043342:web:75e770790d49b5e08bbb5f',
    messagingSenderId: '223831043342',
    projectId: 'smart-warehouse-monitori-1d232',
    authDomain: 'smart-warehouse-monitori-1d232.firebaseapp.com',
    storageBucket: 'smart-warehouse-monitori-1d232.firebasestorage.app',
    measurementId: 'G-B4V5K81P14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwA46WTcA7n4Gioqo0XHwi5zPcJYmDu8',
    appId: '1:223831043342:android:5666f4570ba40dc38bbb5f',
    messagingSenderId: '223831043342',
    projectId: 'smart-warehouse-monitori-1d232',
    storageBucket: 'smart-warehouse-monitori-1d232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSuVAJ8rHMQEVY9klrRcBYUXXwCoY2s4',
    appId: '1:223831043342:ios:fc7cea415ece1ee98bbb5f',
    messagingSenderId: '223831043342',
    projectId: 'smart-warehouse-monitori-1d232',
    storageBucket: 'smart-warehouse-monitori-1d232.firebasestorage.app',
    iosBundleId: 'com.example.smartWarehouseMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSuVAJ8rHMQEVY9klrRcBYUXXwCoY2s4',
    appId: '1:223831043342:ios:fc7cea415ece1ee98bbb5f',
    messagingSenderId: '223831043342',
    projectId: 'smart-warehouse-monitori-1d232',
    storageBucket: 'smart-warehouse-monitori-1d232.firebasestorage.app',
    iosBundleId: 'com.example.smartWarehouseMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMZYd6yj8Wpg-m43E71HhObEDPmWknysQ',
    appId: '1:223831043342:web:34f51231eb92fd788bbb5f',
    messagingSenderId: '223831043342',
    projectId: 'smart-warehouse-monitori-1d232',
    authDomain: 'smart-warehouse-monitori-1d232.firebaseapp.com',
    storageBucket: 'smart-warehouse-monitori-1d232.firebasestorage.app',
    measurementId: 'G-L0BQYH0YC0',
  );

}